"""Add car_registration column

Revision ID: 66a48b827fa7
Revises: 
Create Date: 2025-02-07 15:26:56.391649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a48b827fa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_registration', sa.String(length=20), nullable=True))
        batch_op.drop_index('idx_lead_creator_id')
        batch_op.drop_index('idx_lead_followup_date')
        batch_op.drop_index('idx_lead_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index('idx_lead_status', ['status'], unique=False)
        batch_op.create_index('idx_lead_followup_date', ['followup_date'], unique=False)
        batch_op.create_index('idx_lead_creator_id', ['creator_id'], unique=False)
        batch_op.drop_column('car_registration')

    # ### end Alembic commands ###
