"""Add WorkedLead table for tracking worked leads

Revision ID: add_worked_lead_tracking
Revises: 0f9ae4bf681e
Create Date: 2025-02-07 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_worked_lead_tracking'
down_revision = '0f9ae4bf681e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worked_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('old_followup_date', sa.DateTime(), nullable=True),
    sa.Column('new_followup_date', sa.DateTime(), nullable=False),
    sa.Column('worked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'user_id', 'work_date', name='unique_worked_lead_per_day')
    )
    
    # Create indexes for better performance
    with op.batch_alter_table('worked_lead', schema=None) as batch_op:
        batch_op.create_index('idx_worked_lead_user_date', ['user_id', 'work_date'], unique=False)
        batch_op.create_index('idx_worked_lead_lead_id', ['lead_id'], unique=False)
        batch_op.create_index('idx_worked_lead_work_date', ['work_date'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worked_lead')
    # ### end Alembic commands ### 